# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ef874295314d8ebb82802e08eab32bb004a3663bffc6a745b3e6704f66f7e19e265bb9958b16d5dbf92711ba9b001a5bf7518d3dafb6f5923a46c81223d34b5

test:
  secret_key_base: fa4bcd43b8bc03dc7f718979e6f0b44cbadd06700b485c2e7a150aae37fddb133095eedc56097dc61daa6f3c6752d251e2a1404e41df156ac6e8f7f58df2128b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
